linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - revive
    - unused

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  exclude-dirs:
    - bin
    - vendor

output:
  formats:
    - format: colored-line-number

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck