linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - revive

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck