language: go
install: true
go:
  - 1.6.3
  - 1.7.1
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.1

install:
    - go get -d -v ./...

script:
    - CGO_ENABLED=0 go build -v ./...
