language: go

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64

install:
    - go get -d -v ./...

script:
    - go build -v ./...
    
deploy:
  provider: releases
  api_key: "xz7Aq7tc7kRd7vzw1MHK"
  file: "$HOME/gopath/src/github.com/gi4nks/ambros/ambros"
  skip_cleanup: true
  on:
    tags: false
