language: go

go:
- 1.0.3
- 1.1.2
- 1.2.2
- 1.3.3
- 1.4.2

os:
  - linux
  - osx
  
deploy:
  provider: releases
  api_key: "xz7Aq7tc7kRd7vzw1MHK"
  file: "ambros"
  skip_cleanup: true
  on:
    tags: true